name: Test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  style:
    name: Style
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pipx run flake8
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pipx run pytest --doctest-glob='*.md'
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pipx run build
